### ISSUE TITLE
[Feature request] Add support for https://www.youtube.com/live/<video_id> links

### ISSUE THREAD

**Issue by win98se** [navi1995/YoutubeWindowedFullScreen#3]
They're also accessible as `https://www.youtube.com/watch?v=<video_id>`, but for live videos, the links now default to `https://www.youtube.com/live/<video_id>`.

**Comment by navi1995** [comment]
@win98se good catch! Thanks for letting me know, I'll push a change soon

**Comment by navi1995** [comment]
Update has been published to both chrome and firefox, thanks for raising it :)
